spring:
  redis:
    host: localhost
    port: 6379
    database: 5
    timeout: 60000
    jedis:
      pool:
        max-active: 1000
        max-wait: -1
        max-idle: 10
        min-idle: 5
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      master:
        #url: jdbc:mysql://127.0.0.1:3306/sword?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        #username: root
        #password: 123456
        url: jdbc:mysql://bj-cdb-fmgl4u90.sql.tencentcdb.com:61237/sword?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: sword
        password: '%Password%!123456'
      slave:
        enabled: false
        url: null
        username: null
        password: null
      initialSize: 5
      minIdle: 10
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      maxEvictableIdleTimeMillis: 900000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        allow: null
        url-pattern: /druid/*
        login-username: null
        login-password: null
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

shiro:
  user:
    captchaEnabled: false
    captchaType: char

wallet:
  zbx:
    ticker:
      market: market
      one-url: https://api.zbx.one/data/api/v1/getTicker
      plus-url: https://api.hexhk.com/data/api/v1/getTicker
    url: https://test.hexhk.com
    access-key: 8e03db41-68ae-4445-92f1-d6e7f88e27a6
    secret-key: f4c4dd54f42d7dcb1f3081c507a7927d87b8cc23
    get-deposit-address: /exchange-main/open/v1/test/getDepositAddress
    withdrawal: /exchange-main/open/v1/test/withdrawal
    check-deposit-address: /exchange-main/open/v1/test/checkDepositAddress
    get-user-fund: /exchange-main/open/v1/test/getUserFund 