sword:
  name: Sword
  version: 1.0.0
  copyrightYear: 2021
  profile: sword
  addressEnabled: false
  emailCode: true
  notifyEnabled: false
  upload: 
    baseUrl: https://sword-1258380464.cos.ap-beijing.myqcloud.com
    accessKey: AKID56zkKjmNyjLp8FDPn0sa9XkmfQzOKolY
    bucket: sword-1258380464
    endpoint: ap-beijing
    secretKey: lOtGNJ7kCSZXKwSp12tbAXnuseEfy87v
    addDatePath: true
  code:
    sendcloud: 
      api-user: ubg_user 
      api-key: 969f94332ee41793940f2681ddbb1aae
      region: CN
      from-name: BGA
      from: contract@support.bga.world
      subject: '验证码（Verification Code）'
      template: '<html><body><h3>亲爱的用户，</h3><p>你的验证码是： <strong>{}</strong>，请在5分钟之内使用！</p><h3>Dear user</h3><p>Your verification code is <strong>{}</strong>, Please use within 5 minutes!</p></body></html>'

server:
  port: 8080
  servlet:
    context-path: /admin
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 800
      min-spare: 30
logging:
  level:
    com.soyatec.sword: debug
    org.springframework: warn
user:
  password:
    maxRetryCount: 5
spring:
  thymeleaf:
    mode: HTML
    encoding: utf-8
    cache: false
  messages:
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    generator:
      write-bigdecimal-as-plain: true
      write-numbers-as-strings: true
  profiles:
    active: #profileActive#
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 50MB
mybatis:
  typeAliasesPackage: com.soyatec.sword.**.domain
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  configLocation: classpath:mybatis/mybatis-config.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
shiro:
  user:
    loginUrl: /login
    unauthorizedUrl: /unauth
    indexUrl: /index
    captchaEnabled: true
    captchaType: math
  cookie:
    domain: null
    path: /
    httpOnly: true
    maxAge: 30
    cipherKey: E6675wkXJ0g6+DaThLyQUA==
  session:
    expireTime: 10
    dbSyncPeriod: 1
    validationInterval: 10
    maxSession: 1
    kickoutAfter: false
xss:
  enabled: true
  excludes: /system/notice/*
  urlPatterns: /system/*,/monitor/*,/tool/*