sword:
  name: sword
  version: 1.0.0
  copyrightYear: 2021
  profile: sword
  addressEnabled: false
server:
  port: 8051
  servlet:
    context-path: /admin
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 30
logging:
  level:
    com.soyatec.sword: debug
    org.springframework: warn
user:
  password:
    maxRetryCount: 5
spring:
  thymeleaf:
    mode: HTML
    encoding: utf-8
    cache: false
  messages:
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    generator:
      write-bigdecimal-as-plain: true
      write-numbers-as-strings: true
  profiles:
    active: #profileActive#
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 50MB
  devtools:
    restart:
      enabled: true
mybatis:
  typeAliasesPackage: com.soyatec.sword.**.domain
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  configLocation: classpath:mybatis/mybatis-config.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
shiro:
  user:
    loginUrl: /login
    unauthorizedUrl: /unauth
    indexUrl: /index
    captchaEnabled: true
    captchaType: char
  cookie:
    domain: null
    path: /
    httpOnly: true
    maxAge: 30
    cipherKey: E6675wkXJ0g6+DaThLyQUA==
  session:
    expireTime: 30
    dbSyncPeriod: 1
    validationInterval: 10
    maxSession: -1
    kickoutAfter: false
xss:
  enabled: true
  excludes: /system/notice/*
  urlPatterns: /system/*,/monitor/*,/tool/*